// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BingoBoard struct {
	ID       pgtype.UUID        `json:"id"`
	Category string             `json:"category"`
	Title    string             `json:"title"`
	Date     pgtype.Date        `json:"date"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
	IsActive bool               `json:"is_active"`
}

type BingoCell struct {
	ID          pgtype.UUID `json:"id"`
	BoardID     pgtype.UUID `json:"board_id"`
	MissionCode string      `json:"mission_code"`
	RowIndex    int32       `json:"row_index"`
	ColIndex    int32       `json:"col_index"`
}

type BingoLineReward struct {
	ID          pgtype.UUID `json:"id"`
	BoardID     pgtype.UUID `json:"board_id"`
	ClaimOrder  int32       `json:"claim_order"`
	RewardType  string      `json:"reward_type"`
	RewardRefID pgtype.UUID `json:"reward_ref_id"`
	Quantity    int32       `json:"quantity"`
}

type CraftingRecord struct {
	ID                   pgtype.UUID        `json:"id"`
	PlayerID             pgtype.UUID        `json:"player_id"`
	RecipeCode           string             `json:"recipe_code"`
	InputPlayerSitoneID  pgtype.UUID        `json:"input_player_sitone_id"`
	InputItemCode        string             `json:"input_item_code"`
	OutputPlayerSitoneID pgtype.UUID        `json:"output_player_sitone_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type Match struct {
	ID                 pgtype.UUID        `json:"id"`
	Mode               string             `json:"mode"`
	Status             string             `json:"status"`
	InitiatorPlayerID  pgtype.UUID        `json:"initiator_player_id"`
	OpponentPlayerID   pgtype.UUID        `json:"opponent_player_id"`
	OpponentSnapshotID pgtype.UUID        `json:"opponent_snapshot_id"`
	WorldBossStageID   pgtype.UUID        `json:"world_boss_stage_id"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type MatchAnswer struct {
	ID                pgtype.UUID        `json:"id"`
	MatchQuestionID   pgtype.UUID        `json:"match_question_id"`
	PlayerID          pgtype.UUID        `json:"player_id"`
	SelectedOptionKey *string            `json:"selected_option_key"`
	IsCorrect         bool               `json:"is_correct"`
	ScoreAwarded      int32              `json:"score_awarded"`
	AnsweredAt        pgtype.Timestamptz `json:"answered_at"`
}

type MatchCorrection struct {
	ID              pgtype.UUID        `json:"id"`
	AnswerID        pgtype.UUID        `json:"answer_id"`
	Reason          string             `json:"reason"`
	OpenPowerEarned int32              `json:"open_power_earned"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type MatchPairing struct {
	ID                pgtype.UUID        `json:"id"`
	InitiatorPlayerID pgtype.UUID        `json:"initiator_player_id"`
	TargetPlayerID    pgtype.UUID        `json:"target_player_id"`
	Status            string             `json:"status"`
	MatchID           pgtype.UUID        `json:"match_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type MatchPlayer struct {
	MatchID         pgtype.UUID `json:"match_id"`
	PlayerID        pgtype.UUID `json:"player_id"`
	Side            string      `json:"side"`
	Score           int32       `json:"score"`
	CorrectCount    int32       `json:"correct_count"`
	OpenPowerEarned int32       `json:"open_power_earned"`
	Result          *string     `json:"result"`
}

type MatchQuestion struct {
	ID              pgtype.UUID `json:"id"`
	MatchID         pgtype.UUID `json:"match_id"`
	QuestionCode    string      `json:"question_code"`
	QuestionOrder   int32       `json:"question_order"`
	QuestionColor   string      `json:"question_color"`
	BaseScore       int32       `json:"base_score"`
	ColorBonusScore int32       `json:"color_bonus_score"`
}

type MissionProgressEvent struct {
	ID            pgtype.UUID        `json:"id"`
	PlayerID      pgtype.UUID        `json:"player_id"`
	MissionCode   string             `json:"mission_code"`
	EventType     string             `json:"event_type"`
	Amount        int32              `json:"amount"`
	ActorPlayerID pgtype.UUID        `json:"actor_player_id"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type OfflineOpponentSnapshot struct {
	ID                pgtype.UUID        `json:"id"`
	SourcePlayerID    pgtype.UUID        `json:"source_player_id"`
	DisplayName       string             `json:"display_name"`
	LoadoutSnapshot   []byte             `json:"loadout_snapshot"`
	RecentPerformance []byte             `json:"recent_performance"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type OpenPowerLedger struct {
	ID         pgtype.UUID        `json:"id"`
	PlayerID   pgtype.UUID        `json:"player_id"`
	Amount     int32              `json:"amount"`
	Reason     string             `json:"reason"`
	SourceType string             `json:"source_type"`
	SourceID   pgtype.UUID        `json:"source_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Player struct {
	ID                 pgtype.UUID        `json:"id"`
	TeamID             pgtype.UUID        `json:"team_id"`
	DisplayName        string             `json:"display_name"`
	AvatarUrl          *string            `json:"avatar_url"`
	AuthToken          string             `json:"auth_token"`
	AuthTokenCreatedAt pgtype.Timestamptz `json:"auth_token_created_at"`
	QrToken            string             `json:"qr_token"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type PlayerBingoLineClaim struct {
	PlayerID          pgtype.UUID        `json:"player_id"`
	BingoLineRewardID pgtype.UUID        `json:"bingo_line_reward_id"`
	LineKey           string             `json:"line_key"`
	ClaimedAt         pgtype.Timestamptz `json:"claimed_at"`
}

type PlayerItem struct {
	PlayerID  pgtype.UUID        `json:"player_id"`
	ItemCode  string             `json:"item_code"`
	Quantity  int32              `json:"quantity"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlayerMissionProgress struct {
	ID            pgtype.UUID        `json:"id"`
	PlayerID      pgtype.UUID        `json:"player_id"`
	MissionCode   string             `json:"mission_code"`
	ProgressCount int32              `json:"progress_count"`
	Status        string             `json:"status"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type PlayerSitone struct {
	ID         pgtype.UUID        `json:"id"`
	PlayerID   pgtype.UUID        `json:"player_id"`
	SitoneCode string             `json:"sitone_code"`
	SourceType string             `json:"source_type"`
	SourceID   pgtype.UUID        `json:"source_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type PlayerSitoneLoadoutSlot struct {
	PlayerID       pgtype.UUID        `json:"player_id"`
	SlotIndex      int32              `json:"slot_index"`
	PlayerSitoneID pgtype.UUID        `json:"player_sitone_id"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RewardGrant struct {
	ID          pgtype.UUID        `json:"id"`
	PlayerID    pgtype.UUID        `json:"player_id"`
	TeamID      pgtype.UUID        `json:"team_id"`
	SourceType  string             `json:"source_type"`
	SourceID    pgtype.UUID        `json:"source_id"`
	RewardType  string             `json:"reward_type"`
	RewardRefID pgtype.UUID        `json:"reward_ref_id"`
	Quantity    int32              `json:"quantity"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Team struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TeamBaseThemeSelection struct {
	TeamID        pgtype.UUID        `json:"team_id"`
	BaseThemeCode string             `json:"base_theme_code"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TeamBaseThemeUnlock struct {
	TeamID        pgtype.UUID        `json:"team_id"`
	BaseThemeCode string             `json:"base_theme_code"`
	SourceType    string             `json:"source_type"`
	SourceID      pgtype.UUID        `json:"source_id"`
	UnlockedAt    pgtype.Timestamptz `json:"unlocked_at"`
}

type WorldBoss struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WorldBossAttempt struct {
	ID          pgtype.UUID        `json:"id"`
	StageID     pgtype.UUID        `json:"stage_id"`
	PlayerID    pgtype.UUID        `json:"player_id"`
	MatchID     pgtype.UUID        `json:"match_id"`
	DamageDealt int32              `json:"damage_dealt"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WorldBossProgressEvent struct {
	ID         pgtype.UUID        `json:"id"`
	StageID    pgtype.UUID        `json:"stage_id"`
	PlayerID   pgtype.UUID        `json:"player_id"`
	TeamID     pgtype.UUID        `json:"team_id"`
	SourceType string             `json:"source_type"`
	SourceID   pgtype.UUID        `json:"source_id"`
	Damage     int32              `json:"damage"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type WorldBossStage struct {
	ID                      pgtype.UUID        `json:"id"`
	WorldBossID             pgtype.UUID        `json:"world_boss_id"`
	StageIndex              int32              `json:"stage_index"`
	Name                    string             `json:"name"`
	MaxHp                   int32              `json:"max_hp"`
	CurrentHp               int32              `json:"current_hp"`
	ChallengeLimitPerPlayer int32              `json:"challenge_limit_per_player"`
	TopicWeightConfig       []byte             `json:"topic_weight_config"`
	Status                  string             `json:"status"`
	UnlockedAt              pgtype.Timestamptz `json:"unlocked_at"`
	DefeatedAt              pgtype.Timestamptz `json:"defeated_at"`
}
