// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system.sql

package sqlc

import (
	"context"
)

const getDatabaseTime = `-- name: GetDatabaseTime :one
SELECT now()::text AS database_time
`

func (q *Queries) GetDatabaseTime(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getDatabaseTime)
	var database_time string
	err := row.Scan(&database_time)
	return database_time, err
}
