// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Confirms the API process is running.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Hello world",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.MessageResponse"
                        }
                    }
                }
            }
        },
        "/examples/validation": {
            "post": {
                "description": "Demonstrates JSON decode errors, validator semantic errors, and array-level error locations.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "examples"
                ],
                "summary": "Validation example",
                "parameters": [
                    {
                        "description": "Validation example request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/example.ValidationExampleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/example.ValidationExampleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpx.ProblemDetails"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httpx.ProblemDetails"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Confirms the HTTP process is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.StatusResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Runs a minimal sqlc query to confirm database access.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Database ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.PingResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/httpx.ProblemDetails"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Confirms required dependencies are reachable.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.StatusResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/httpx.ProblemDetails"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "example.PlayerInput": {
            "type": "object",
            "required": [
                "displayName",
                "favoritePebbleType",
                "teamNumber"
            ],
            "properties": {
                "displayName": {
                    "type": "string",
                    "maxLength": 40
                },
                "favoritePebbleType": {
                    "type": "string",
                    "enum": [
                        "exploration",
                        "inspiration",
                        "resonance",
                        "engineering",
                        "entertainment"
                    ]
                },
                "teamNumber": {
                    "type": "integer",
                    "maximum": 20,
                    "minimum": 1
                }
            }
        },
        "example.ValidationExampleRequest": {
            "type": "object",
            "required": [
                "players"
            ],
            "properties": {
                "players": {
                    "type": "array",
                    "maxItems": 20,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/example.PlayerInput"
                    }
                }
            }
        },
        "example.ValidationExampleResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "validation example accepted"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/example.PlayerInput"
                    }
                }
            }
        },
        "httpx.ErrorDetail": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "httpx.ProblemDetails": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpx.ErrorDetail"
                    }
                },
                "instance": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "system.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Camp 2026 Game API is running"
                }
            }
        },
        "system.PingResponse": {
            "type": "object",
            "properties": {
                "databaseTime": {
                    "type": "string",
                    "example": "2026-05-29 12:00:00.000000+00"
                },
                "message": {
                    "type": "string",
                    "example": "pong"
                }
            }
        },
        "system.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Camp 2026 Game API",
	Description:      "Backend API for the SITCON Camp 2026 game.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
